[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"

solc = "/opt/homebrew/bin/solc"
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"

fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

